bird_species_info = {
    "Abroscopus-superciliaris": {"name_en": "Yellow-browed Tit", "name_th": "นกกระจิบเขียวคิ้วเหลือง"},
    "Alcedo-atthis": {"name_en": "Common Kingfisher", "name_th": "นกกินเปี้ยวเล็ก"},
    "Alophoixus-pallidus": {"name_en": "Puff-throated Bulbul", "name_th": "นกปรอดคอพอง"},
    "Anthus-hodgsoni": {"name_en": "Olive-backed Pipit", "name_th": "นกเด้าดินหลังเขียว"},
    "Cacomantis-merulinus": {"name_en": "Plaintive Cuckoo", "name_th": "นกอีวาบตั๊กแตน"},
    "Cacomantis-sonneratii": {"name_en": "Banded Bay Cuckoo", "name_th": "นกอีวาบท้องแดง"},
    "Centropus-bengalensis": {"name_en": "Lesser Coucal", "name_th": "นกกระปูดเล็ก"},
    "Centropus-sinensis": {"name_en": "Greater Coucal", "name_th": "นกกระปูดใหญ่"},
    "Ceryle-rudis": {"name_en": "Pied Kingfisher", "name_th": "นกกะเต็นลาย"},
    "Chrysocolaptes-guttacristatus": {"name_en": "Greater Flameback", "name_th": "นกหัวขวานใหญ่หลังทอง"},
    "Coracias-benghalensis": {"name_en": "Indian Roller", "name_th": "นกตะขาบทุ่ง"},
    "Culicicapa-ceylonensis": {"name_en": "Grey-headed Canary-flycatcher", "name_th": "นกจับแมลงหัวเทา"},
    "Cyornis-whitei": {"name_en": "White-tailed Flycatcher", "name_th": "นกจับแมลงหางขาว"},
    "Dicrurus-leucophaeus": {"name_en": "Ashy Drongo", "name_th": "นกแซงแซวสีเทา"},
    "Dicrurus-remifer": {"name_en": "Lesser Racket-tailed Drongo", "name_th": "นกแซงแซวหางพัดเล็ก"},
    "Erpornis-zantholeuca": {"name_en": "White-bellied Erpornis", "name_th": "นกกินปลีหัวเทา"},
    "Eudynamys-scolopaceus": {"name_en": "Asian Koel", "name_th": "นกกาเหว่า"},
    "Gallus-gallus": {"name_en": "Red Junglefowl", "name_th": "ไก่ป่า"},
    "Glaucidium-cuculoides": {"name_en": "Asian Barred Owlet", "name_th": "นกเค้าลายหยัก"},
    "Harpactes-erythrocephalus": {"name_en": "Red-headed Trogon", "name_th": "นกพญาไฟหัวแดง"},
    "Harpactes-oreskios": {"name_en": "Orange-breasted Trogon", "name_th": "นกพญาไฟอกส้ม"},
    "Hierococcyx-sparverioides": {"name_en": "Large Hawk-Cuckoo", "name_th": "นกอีวาบใหญ่"},
    "Hirundo-rustica": {"name_en": "Barn Swallow", "name_th": "นกนางแอ่นบ้าน"},
    "Hypothymis-azurea": {"name_en": "Black-naped Monarch", "name_th": "นกจับแมลงจุกฟ้า"},
    "Hypsipetes-leucocephalus": {"name_en": "Black Bulbul", "name_th": "นกปรอดดำ"},
    "Ixos-mcclellandii": {"name_en": "Mountain Bulbul", "name_th": "นกปรอดเขา"},
    "Merops-leschenaulti": {"name_en": "Chestnut-headed Bee-eater", "name_th": "นกจาบคาหัวสีน้ำตาลแดง"},
    "Merops-orientalis": {"name_en": "Green Bee-eater", "name_th": "นกจาบคาเล็ก"},
    "Myiomela-leucura": {"name_en": "White-tailed Robin", "name_th": "นกเขนหางขาว"},
    "Nyctyornis-athertoni": {"name_en": "Blue-bearded Bee-eater", "name_th": "นกจาบคาหน้าบาก"},
    "Parus-minor": {"name_en": "Japanese Tit", "name_th": "นกติตญี่ปุ่น"},
    "Pericrocotus-speciosus": {"name_en": "Scarlet Minivet", "name_th": "นกพญาไฟสีแสด"},
    "Phaenicophaeus-tristis": {"name_en": "Green-billed Malkoha", "name_th": "นกบั้งรอกใหญ่"},
    "Phoenicurus-auroreus": {"name_en": "Daurian Redstart", "name_th": "นกเขนแดง"},
    "Phyllergates-cucullatus": {"name_en": "Mountain Tailorbird", "name_th": "นกกระจิบภูเขา"},
    "Phylloscopus-inornatus": {"name_en": "Yellow-browed Warbler", "name_th": "นกกระจิบคิ้วเหลือง"},
    "Phylloscopus-omeiensis": {"name_en": "Martens's Warbler", "name_th": "นกกระจิบมาร์เทนส์"},
    "Picumnus-innominatus": {"name_en": "Speckled Piculet", "name_th": "นกหัวขวานจิ๋วลายจุด"},
    "Psilopogon-asiaticus": {"name_en": "Blue-throated Barbet", "name_th": "นกโพระดกคางฟ้า"},
    "Psilopogon-haemacephalus": {"name_en": "Coppersmith Barbet", "name_th": "นกตีทอง"},
    "Psilopogon-lineatus": {"name_en": "Lineated Barbet", "name_th": "นกโพระดกหัวขีด"},
    "Psilopogon-virens": {"name_en": "Great Barbet", "name_th": "นกโพระดกใหญ่"},
    "Pycnonotus-aurigaster": {"name_en": "Sooty-headed Bulbul", "name_th": "นกปรอดหัวสีเขม่า"},
    "Saxicola-stejnegeri": {"name_en": "Stejneger's Stonechat", "name_th": "นกจู๋เต้นสเทจนีเกอร์"},
    "Spilopelia-chinensis": {"name_en": "Spotted Dove", "name_th": "นกเขาใหญ่"},
    "Surniculus-lugubris": {"name_en": "Drongo Cuckoo", "name_th": "นกคัคคูแซงแซว"},
    "Turnix-suscitator": {"name_en": "Barred Buttonquail", "name_th": "นกกระทาเหยี่ยว"},
    "Turnix-tanki": {"name_en": "Yellow-legged Buttonquail", "name_th": "นกกระทาเท้าเหลือง"},
    "Upupa-epops": {"name_en": "Eurasian Hoopoe", "name_th": "นกกะรางหัวขวาน"},
    "Urosphena-squameiceps": {"name_en": "Scaly-breasted Wren-babbler", "name_th": "นกกินแมลงอกเกล็ด"},
    "Yungipicus-canicapillus": {"name_en": "Grey-capped Pygmy Woodpecker", "name_th": "นกหัวขวานเล็กหัวเทา"},
}

insect_species_info = {
    "Acheta-domesticus": {"name_en": "House Cricket", "name_th": "จิ้งหรีดบ้าน"},
    "Conocephalus-fuscus": {"name_en": "Lesser Marsh Katydid", "name_th": "ตั๊กแตนหนวดยาวทุ่ง"},
    "Eumodicogryllus-bordigalensis": {"name_en": "Mediterranean Field Cricket", "name_th": "จิ้งหรีดสนามยุโรป"},
    "Galangal-abeculata": {"name_en": "Galangal Cricket", "name_th": "จิ้งหรีดกระชาย"},
    "Gryllus-bimaculatus": {"name_en": "Two-spotted Cricket", "name_th": "จิ้งหรีดสองจุด"},
    "Oecanthus-pellucens": {"name_en": "Transparent Tree Cricket", "name_th": "จิ้งหรีดต้นไม้โปร่งแสง"},
    "Phaneroptera-falcata": {"name_en": "Sickle-bearing Bush-cricket", "name_th": "ตั๊กแตนใบไม้ปีกโค้ง"},
    "Phaneroptera-nana": {"name_en": "Southern Bush-cricket", "name_th": "ตั๊กแตนใบไม้ใต้"},
}

SPECIES_INFO = {**bird_species_info, **insect_species_info}
